name: imm_radio
description: "Intentional Marriage Ministries media app"
publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.12
  firebase_core: ^3.4.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2

  flutter_localizations:
    sdk: flutter
  intl: any
  url_launcher: ^6.3.0
  video_player: ^2.8.1
  flutter_inappwebview: 6.1.5 # for DOC/TXT/HTML viewing
  youtube_player_flutter: 9.1.2
  syncfusion_flutter_pdfviewer: ^31.2.3
  share_plus: ^10.0.0
  shared_preferences: ^2.2.0
  connectivity_plus: ^6.0.3
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
 


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/branding_icon.png
    - assets/images/splash_gradient.png
    

# -------------------------
# -------------------------
# flutter_native_splash config
# -------------------------
#flutter_native_splash:
  #color: "#5E35B1"           # background (Deep Purple)
  #background_image: assets/images/splash_gradient.png
  #image: assets/images/logo.png     # make sure this file exists
  #branding: assets/images/branding_icon.png
  #android: true
  #ios: true
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1a1a1a" # optional background for Android
